### ISSUE TITLE
Bot events don't work anymore

### ISSUE THREAD

**Issue by TimBitBox** [XuaTheGrate/slash_util#13]
bot events don't work anymore:
`
@bot.event
def on_ready():
    # something
`
returns error: `TypeError: event() missing 1 required positional argument: 'coro'`
And bot is my slash_util init cog

**Comment by XuaTheGrate** [comment]
- This is not an issue with slash_util
- You attempted to use `@bot.event()`, parenthesis included. This decorator does not use parenthesis.

For future questions, please ask in the [discord.py server](https://discord.gg/dpy)
