### ISSUE TITLE
Plan to publish to pypi?

### ISSUE THREAD

**Issue by timelessnesses** [XuaTheGrate/slash_util#5]
Maybe publish to pypi so users can install straight from pip instead of copy from github?

**Comment by XuaTheGrate** [comment]
This is planned and I'll get around to it sooner or later.

**Comment by XuaTheGrate** [comment]
This should be complete now. If any further issues arise feel free to comment on this issue.

https://pypi.org/project/slash-util/

**Comment by timelessnesses** [comment]
>:0
